// Generated by CoffeeScript 1.7.1
(function() {
  var env, vm;

  shine.stdout.write = function() {
    return console.log.apply(console, arguments);
  };

  env = {
    love: new Love()
  };

  vm = new shine.VM(env);

  vm.load('./lua/boot.lua.json');

}).call(this);

//# sourceMappingURL=amore.map
