// Generated by CoffeeScript 1.7.1
(function() {
  var conf;

  shine.stdout.write = function() {
    return console.log.apply(console, arguments);
  };

  conf = {
    window: {}
  };

  new shine.FileManager().load('./lua/conf.lua.json', function(_, file) {
    var conf_env, conf_vm, vm;
    conf_env = {
      love: {}
    };
    conf_vm = new shine.VM(conf_env);
    conf_vm.execute(null, file);
    conf_env.love.conf.call(null, conf);
    vm = new shine.VM({
      love: new Love(conf.window)
    });
    return vm.load('./lua/boot.lua.json');
  });

}).call(this);

//# sourceMappingURL=amore.map
