// Generated by CoffeeScript 1.7.1
(function() {
  var Color, Graphics, Timer,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Graphics = (function() {
    function Graphics() {
      this.setBackgroundColor = __bind(this.setBackgroundColor, this);
      this.setColor = __bind(this.setColor, this);
      this.rectangle = __bind(this.rectangle, this);
      this.printf = __bind(this.printf, this);
      this.print = __bind(this.print, this);
      this.present = __bind(this.present, this);
      this.polygon = __bind(this.polygon, this);
      this.point = __bind(this.point, this);
      this.line = __bind(this.line, this);
      this.clear = __bind(this.clear, this);
      this.circle = __bind(this.circle, this);
      this.arc = __bind(this.arc, this);
      this.canvas = document.createElement('canvas');
      this.canvas.setAttribute('width', 200);
      this.canvas.setAttribute('height', 200);
      document.body.appendChild(this.canvas);
      this.ctx = this.canvas.getContext('2d');
      this.setColor(255, 255, 255);
      this.setBackgroundColor(0, 0, 0);
    }

    Graphics.prototype.arc = function() {};

    Graphics.prototype.circle = function() {};

    Graphics.prototype.clear = function() {
      this.ctx.save();
      this.ctx.setTransform(1, 0, 0, 1, 0, 0);
      this.ctx.fillStyle = this.background_color.html_code;
      this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
      return this.ctx.restore();
    };

    Graphics.prototype.line = function() {};

    Graphics.prototype.point = function() {};

    Graphics.prototype.polygon = function() {};

    Graphics.prototype.present = function() {};

    Graphics.prototype.print = function(str, x, y) {
      return this.ctx.fillText(str, x, y);
    };

    Graphics.prototype.printf = function() {};

    Graphics.prototype.rectangle = function(mode, x, y, width, height) {
      switch (mode) {
        case "fill":
          return this.ctx.fillRect(x, y, width, height);
        case "line":
          return this.ctx.strokeRect(x, y, width, height);
      }
    };

    Graphics.prototype.setColor = function(r, g, b, a) {
      if (a == null) {
        a = 255;
      }
      this.current_color = new Color(r, g, b, a);
      this.ctx.fillStyle = this.current_color.html_code;
      return this.ctx.strokeStyle = this.current_color.html_code;
    };

    Graphics.prototype.setBackgroundColor = function(r, g, b, a) {
      if (a == null) {
        a = 255;
      }
      return this.background_color = new Color(r, g, b, a);
    };

    return Graphics;

  })();

  this.Love = (function() {
    function Love() {
      this.run = __bind(this.run, this);
      this.set_callbacks = __bind(this.set_callbacks, this);
      this.graphics = new Graphics();
      this.timer = new Timer();
    }

    Love.prototype.set_callbacks = function(load, update, draw) {
      this.load = load;
      this.update = update;
      return this.draw = draw;
    };

    Love.prototype.run = function() {
      var game_loop;
      this.timer.step();
      this.load.call();
      game_loop = (function(_this) {
        return function() {
          _this.timer.step();
          _this.update.call(null, _this.timer.getDelta());
          _this.graphics.clear();
          _this.draw.call();
          return _this.timer.nextFrame(game_loop);
        };
      })(this);
      return this.timer.nextFrame(game_loop);
    };

    return Love;

  })();

  Timer = (function() {
    var lastTime, performance, requestAnimationFrame;

    function Timer() {
      this.step = __bind(this.step, this);
      this.sleep = __bind(this.sleep, this);
      this.getTime = __bind(this.getTime, this);
      this.getFPS = __bind(this.getFPS, this);
      this.getDelta = __bind(this.getDelta, this);
      this.nextFrame = __bind(this.nextFrame, this);
      this.microTime = performance.now();
      this.deltaTime = 0;
      this.deltaTimeLimit = 0.25;
      this.events = {};
      this.maxEventId = 0;
    }

    Timer.prototype.nextFrame = function(callback) {
      return requestAnimationFrame(callback);
    };

    Timer.prototype.getDelta = function() {
      return this.deltaTime;
    };

    Timer.prototype.getFPS = function() {
      if (this.deltaTime === 0) {
        return 0;
      } else {
        return 1 / this.deltaTime;
      }
    };

    Timer.prototype.getTime = function() {
      return this.microTime;
    };

    Timer.prototype.sleep = function() {};

    Timer.prototype.step = function() {
      var dt;
      dt = (performance.now() - this.microTime) / 1000;
      this.deltaTime = Math.max(0, Math.min(this.deltaTimeLimit, dt));
      return this.microTime += dt * 1000;
    };

    performance = window.performance || Date;

    performance.now = performance.now || performance.msNow || performance.mozNow || performance.webkitNow || Date.now;

    lastTime = 0;

    requestAnimationFrame = window.requestAnimationFrame || window.msRequestAnimationFrame || window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || window.oRequestAnimationFrame || function(callback) {
      var currTime, delay, timeToCall;
      currTime = performance.now();
      timeToCall = Math.max(0, 16 - (currTime - lastTime));
      delay = function() {
        return callback(currTime + timeToCall);
      };
      lastTime = currTime + timeToCall;
      return setTimeout(delay, timeToCall);
    };

    return Timer;

  })();

  Color = (function() {
    function Color(r, g, b, a) {
      this.r = r;
      this.g = g;
      this.b = b;
      this.a = a != null ? a : 255;
      this.html_code = "rgba(" + this.r + ", " + this.g + ", " + this.b + ", " + this.a + ")";
    }

    return Color;

  })();

}).call(this);

//# sourceMappingURL=love.map
